import Navbar from "../navbar";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <div className="bg-blue-50 dark:bg-gray-800 ">
      <Head>
        <title>Data Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      <Navbar />
      <main>{children}</main>
    </div>
  );
};

export default Layout;
